In [163]:
import os
print(os.getcwd())

C:\Users\abhis\IPL_win_Probability_ML

In [164]:
import numpy as np
import pandas as pd

In [165]:
match_df=pd.read_csv("Data/matches.csv")

In [166]:
match_df.head()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [167]:
match_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               756 non-null    int64
 1   Season           756 non-null    object
 2   city             749 non-null    object
 3   date             756 non-null    object
 4   team1            756 non-null    object
 5   team2            756 non-null    object
 6   toss_winner      756 non-null    object
 7   toss_decision    756 non-null    object
 8   result           756 non-null    object
 9   dl_applied       756 non-null    int64
 10  winner           752 non-null    object
 11  win_by_runs      756 non-null    int64
 12  win_by_wickets   756 non-null    int64
 13  player_of_match  752 non-null    object
 14  venue            756 non-null    object
 15  umpire1          754 non-null    object
 16  umpire2          754 non-null    object
 17  umpire3          119 non-null    object
dtypes: int64(4), object(14)
memory usage: 106.4+ KB

In [168]:
match_df.shape

(756, 18)

In [169]:
match_df.describe()

                 id  dl_applied  win_by_runs  win_by_wickets
count    756.000000  756.000000   756.000000      756.000000
mean    1792.178571    0.025132    13.283069        3.350529
std     3464.478148    0.156630    23.471144        3.387963
min        1.000000    0.000000     0.000000        0.000000
25%      189.750000    0.000000     0.000000        0.000000
50%      378.500000    0.000000     0.000000        4.000000
75%      567.250000    0.000000    19.000000        6.000000
max    11415.000000    1.000000   146.000000       10.000000

In [170]:
match_df.columns.values

array(['id', 'Season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'], dtype=object)

In [171]:
match_df.drop(['date','city','result','win_by_runs','win_by_runs','win_by_wickets','player_of_match','umpire1','umpire2','umpire3'],axis=1,inplace=True)

In [172]:
match_df.shape

(756, 9)

In [173]:
match_df['Season'].dtype

dtype('O')

In [174]:
match_df['Season_year']=match_df['Season'].str.extract(r'(\d{4})').astype(int)
match_df=match_df.drop('Season',axis=1)

In [175]:
match_df.head()

,id,team1,team2,toss_winner,toss_decision,dl_applied,winner,venue,Season_year
0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,0,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017
1,2,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,0,Rising Pune Supergiant,Maharashtra Cricket Association Stadium,2017
2,3,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,0,Kolkata Knight Riders,Saurashtra Cricket Association Stadium,2017
3,4,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,0,Kings XI Punjab,Holkar Cricket Stadium,2017
4,5,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,0,Royal Challengers Bangalore,M Chinnaswamy Stadium,2017

In [176]:
match_df.shape

(756, 9)

#### we user r just because we didnt change the backslash to forwardslash ,which the what we do when we use any file path in python pd.read_csv(we copy the path of the file from our local storage and then change the slashes)

In [177]:
teams=pd.read_csv(r"Data\teams.csv")

In [178]:
teams

                          team1
0                 Pune Warriors
1         Kolkata Knight Riders
2              Rajasthan Royals
3          Kochi Tuskers Kerala
4                 Gujarat Lions
5           Chennai Super Kings
6       Rising Pune Supergiants
7              Delhi Daredevils
8               Deccan Chargers
9                Delhi Capitals
10               Mumbai Indians
11          Sunrisers Hyderabad
12       Rising Pune Supergiant
13  Royal Challengers Bangalore
14              Kings XI Punjab

In [179]:
main_team = ['Sunrisers Hyderabad',
    'Mumbai Indians',
    'Gujarat Titans',
    'Royal Challengers Bangalore',
    'Kolkata Knight Riders',
    'Kings XI Punjab',
    'Chennai Super Kings',
    'Rajasthan Royals',
    'Delhi Capitals']

In [180]:
teams=teams[teams['team1'].isin(main_team)]

In [181]:
teams=teams.reset_index(drop=True)

In [182]:
teams.loc[len(teams),'team1']='Gujarat Titans'

In [183]:
match_df["team1"].unique()

array(['Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders', 'Delhi Daredevils', 'Kings XI Punjab',
       'Chennai Super Kings', 'Rajasthan Royals', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants',
       'Delhi Capitals'], dtype=object)

In [184]:
match_df.shape

(756, 9)

In [185]:
match_df['team1']=match_df['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team2']=match_df['team2'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['toss_winner']=match_df['toss_winner'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['winner']=match_df['winner'].str.replace('Delhi Daredevils','Delhi Capitals')

In [186]:
match_df['team1']=match_df['team1'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')
match_df['team2']=match_df['team2'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')
match_df['toss_winner']=match_df['toss_winner'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')
match_df['winner']=match_df['winner'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')

In [187]:
match_df['team1']=match_df['team1'].str.replace('Gujarat Lions', 'Gujarat Titans')
match_df['team2']=match_df['team2'].str.replace('Gujarat Lions', 'Gujarat Titans')
match_df['toss_winner']=match_df['toss_winner'].str.replace('Gujarat Lions', 'Gujarat Titans')
match_df['winner']=match_df['winner'].str.replace('Gujarat Lions', 'Gujarat Titans')

In [188]:
match_df.shape

(756, 9)

In [189]:
match_df.isnull().sum()

id               0
team1            0
team2            0
toss_winner      0
toss_decision    0
dl_applied       0
winner           4
venue            0
Season_year      0
dtype: int64

In [190]:
match_df=match_df[match_df['team1'].isin(teams['team1']) & match_df['team2'].isin(teams['team1'])]

In [191]:
match_df.shape

(667, 9)

In [192]:
match_df=match_df[match_df['winner'].isin(teams['team1']) | match_df['winner'].isna()&
    match_df['toss_winner'].isin(teams['team1'])]

In [193]:
match_df.shape

(667, 9)

In [194]:
match_df

,id,team1,team2,toss_winner,toss_decision,dl_applied,winner,venue,Season_year
0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,0,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017
2,3,Gujarat Titans,Kolkata Knight Riders,Kolkata Knight Riders,field,0,Kolkata Knight Riders,Saurashtra Cricket Association Stadium,2017
4,5,Royal Challengers Bangalore,Delhi Capitals,Royal Challengers Bangalore,bat,0,Royal Challengers Bangalore,M Chinnaswamy Stadium,2017
5,6,Gujarat Titans,Sunrisers Hyderabad,Sunrisers Hyderabad,field,0,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017
6,7,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,0,Mumbai Indians,Wankhede Stadium,2017
...,...,...,...,...,...,...,...,...,...
751,11347,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,0,Mumbai Indians,Wankhede Stadium,2019
752,11412,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,0,Mumbai Indians,M. A. Chidambaram Stadium,2019
753,11413,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,0,Delhi Capitals,ACA-VDCA Stadium,2019
754,11414,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,0,Chennai Super Kings,ACA-VDCA Stadium,2019
755,11415,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,0,Mumbai Indians,Rajiv Gandhi Intl. Cricket Stadium,2019

In [195]:
match_df['dl_applied'].value_counts()

dl_applied
0    652
1     15
Name: count, dtype: int64

In [196]:
match_df=match_df[match_df['dl_applied']==0]
match_df.shape

(652, 9)

In [197]:
match_df.drop('dl_applied',axis=1,inplace=True)

C:\Users\abhis\AppData\Local\Temp\ipykernel_29356\2897387816.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_df.drop('dl_applied',axis=1,inplace=True)

In [198]:
match_df.shape

(652, 8)

In [199]:
match_df.head()

,id,team1,team2,toss_winner,toss_decision,winner,venue,Season_year
0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017
2,3,Gujarat Titans,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,Saurashtra Cricket Association Stadium,2017
4,5,Royal Challengers Bangalore,Delhi Capitals,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,M Chinnaswamy Stadium,2017
5,6,Gujarat Titans,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017
6,7,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,Wankhede Stadium,2017

In [200]:
match_df.columns

Index(['id', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'venue', 'Season_year'],
      dtype='object')

In [201]:
delivery_df=pd.read_csv("Data/deliveries.csv")

In [202]:
delivery_df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [203]:
delivery_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179078 entries, 0 to 179077
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          179078 non-null  int64
 1   inning            179078 non-null  int64
 2   batting_team      179078 non-null  object
 3   bowling_team      179078 non-null  object
 4   over              179078 non-null  int64
 5   ball              179078 non-null  int64
 6   batsman           179078 non-null  object
 7   non_striker       179078 non-null  object
 8   bowler            179078 non-null  object
 9   is_super_over     179078 non-null  int64
 10  wide_runs         179078 non-null  int64
 11  bye_runs          179078 non-null  int64
 12  legbye_runs       179078 non-null  int64
 13  noball_runs       179078 non-null  int64
 14  penalty_runs      179078 non-null  int64
 15  batsman_runs      179078 non-null  int64
 16  extra_runs        179078 non-null  int64
 17  total_runs        179078 non-null  int64
 18  player_dismissed  8834 non-null    object
 19  dismissal_kind    8834 non-null    object
 20  fielder           6448 non-null    object
dtypes: int64(13), object(8)
memory usage: 28.7+ MB

In [204]:
delivery_df.shape

(179078, 21)

In [205]:
delivery_df.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [206]:
delivery_df.drop(['non_striker','is_super_over','wide_runs','bye_runs','legbye_runs','noball_runs','penalty_runs','dismissal_kind','fielder'],axis=1,inplace=True)

In [207]:
delivery_df.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'bowler', 'batsman_runs', 'extra_runs', 'total_runs',
       'player_dismissed'],
      dtype='object')

In [208]:
delivery_df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,bowler,batsman_runs,extra_runs,total_runs,player_dismissed
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,TS Mills,0,0,0,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,TS Mills,0,0,0,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,TS Mills,4,0,4,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,TS Mills,0,0,0,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,TS Mills,0,2,2,NaN

In [209]:
delivery_df['batting_team'].unique()

array(['Sunrisers Hyderabad', 'Royal Challengers Bangalore',
       'Mumbai Indians', 'Rising Pune Supergiant', 'Gujarat Lions',
       'Kolkata Knight Riders', 'Kings XI Punjab', 'Delhi Daredevils',
       'Chennai Super Kings', 'Rajasthan Royals', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants',
       'Delhi Capitals'], dtype=object)

In [210]:
delivery_df.shape

(179078, 12)

In [211]:
delivery_df['batting_team']=delivery_df['batting_team'].str.replace('Delhi Daredevils','Delhi Capitals')
delivery_df['bowling_team']=delivery_df['bowling_team'].str.replace('Delhi Daredevils','Delhi Capitals')

In [212]:
delivery_df['batting_team']=delivery_df['batting_team'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')
delivery_df['bowling_team']=delivery_df['bowling_team'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')

In [213]:
delivery_df['batting_team']=delivery_df['batting_team'].str.replace('Gujarat Lions', 'Gujarat Titans')
delivery_df['bowling_team']=delivery_df['bowling_team'].str.replace('Gujarat Lions', 'Gujarat Titans')

In [214]:
delivery_df.shape

(179078, 12)

In [215]:
delivery_df=delivery_df[delivery_df['batting_team'].isin(teams['team1']) & delivery_df['bowling_team'].isin(teams['team1'])]

In [216]:
delivery_df.shape

(158205, 12)

In [217]:
delivery_df['batting_team'].unique()

array(['Sunrisers Hyderabad', 'Royal Challengers Bangalore',
       'Gujarat Titans', 'Kolkata Knight Riders', 'Delhi Capitals',
       'Mumbai Indians', 'Kings XI Punjab', 'Chennai Super Kings',
       'Rajasthan Royals'], dtype=object)

In [218]:
delivery_df.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'bowler', 'batsman_runs', 'extra_runs', 'total_runs',
       'player_dismissed'],
      dtype='object')

In [219]:
batsman_stat=(delivery_df.groupby(['batsman']).agg(
    runs=('batsman_runs','sum'),balls_faced=('ball','count')
    ).assign(batsman_sr=lambda x:100*x.runs/x.balls_faced).reset_index())

In [220]:
batsman_stat

            batsman  runs  balls_faced  batsman_sr
0    A Ashish Reddy   254          177  143.502825
1        A Chandila     4            7   57.142857
2          A Chopra    53           75   70.666667
3       A Choudhary    25           20  125.000000
4       A Dananjaya     4            5   80.000000
..              ...   ...          ...         ...
488     YV Takawale   192          183  104.918033
489   Yashpal Singh    47           67   70.149254
490     Younis Khan     3            7   42.857143
491    Yuvraj Singh  2114         1680  125.833333
492          Z Khan   117          141   82.978723

[493 rows x 4 columns]

In [221]:
bowlers_stat=(
    delivery_df.groupby('bowler').agg(
    run_conceded=('total_runs','sum'),
    balls_bowled=('ball','count'),
    wickets_took=('player_dismissed',lambda x:x.notna().sum())
).assign(
        economy=lambda x:6*x.run_conceded/x.balls_bowled,
        wicket_rate=lambda x:6*x.wickets_took/x.balls_bowled
        ).reset_index()
)

In [222]:
bowlers_stat

,bowler,run_conceded,balls_bowled,wickets_took,economy,wicket_rate
0,A Ashish Reddy,315,215,15,8.790698,0.418605
1,A Chandila,209,198,7,6.333333,0.212121
2,A Choudhary,144,108,5,8.000000,0.277778
3,A Dananjaya,48,25,0,11.520000,0.000000
4,A Flintoff,106,66,2,9.636364,0.181818
...,...,...,...,...,...,...
382,YA Abdulla,311,222,15,8.405405,0.405405
383,YK Pathan,1347,1091,38,7.407883,0.208983
384,YS Chahal,2342,1794,101,7.832776,0.337793
385,Yuvraj Singh,737,568,24,7.785211,0.253521
386,Z Khan,2648,2090,108,7.601914,0.310048

In [223]:
delivery_df.shape

(158205, 12)

In [224]:
delivery_df.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'bowler', 'batsman_runs', 'extra_runs', 'total_runs',
       'player_dismissed'],
      dtype='object')

In [225]:
delivery_df=delivery_df.merge(batsman_stat[['batsman','batsman_sr']],on='batsman',how='left')
delivery_df=delivery_df.merge(bowlers_stat[['bowler','economy','wicket_rate']],on='bowler',how='left')

In [226]:
delivery_df.shape

(158205, 15)

In [227]:
delivery_df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,bowler,batsman_runs,extra_runs,total_runs,player_dismissed,batsman_sr,economy,wicket_rate
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,TS Mills,0,0,0,NaN,140.548116,8.486486,0.27027
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,TS Mills,0,0,0,NaN,140.548116,8.486486,0.27027
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,TS Mills,4,0,4,NaN,140.548116,8.486486,0.27027
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,TS Mills,0,0,0,NaN,140.548116,8.486486,0.27027
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,TS Mills,0,2,2,NaN,140.548116,8.486486,0.27027

In [228]:
delivery_df.drop(['batsman','bowler'],axis=1,inplace=True)
delivery_df.shape

(158205, 13)

In [229]:
total_runs=delivery_df.groupby(['match_id','inning']).sum()['total_runs'].reset_index()

In [230]:
total_runs

      match_id  inning  total_runs
0            1       1         207
1            1       2         172
2            3       1         183
3            3       2         184
4            5       1         157
...        ...     ...         ...
1346     11413       2         170
1347     11414       1         155
1348     11414       2         162
1349     11415       1         152
1350     11415       2         157

[1351 rows x 3 columns]

In [231]:
total_runs=total_runs[total_runs['inning']==1]

In [232]:
total_runs

      match_id  inning  total_runs
0            1       1         207
2            3       1         183
4            5       1         157
6            6       1         135
8            7       1         178
...        ...     ...         ...
1341     11347       1         143
1343     11412       1         136
1345     11413       1         171
1347     11414       1         155
1349     11415       1         152

[667 rows x 3 columns]

In [233]:
match_df.rename(columns={'id':'match_id'},inplace=True)

C:\Users\abhis\AppData\Local\Temp\ipykernel_29356\1239321319.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_df.rename(columns={'id':'match_id'},inplace=True)

In [234]:
match_df

,match_id,team1,team2,toss_winner,toss_decision,winner,venue,Season_year
0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017
2,3,Gujarat Titans,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,Saurashtra Cricket Association Stadium,2017
4,5,Royal Challengers Bangalore,Delhi Capitals,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,M Chinnaswamy Stadium,2017
5,6,Gujarat Titans,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017
6,7,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,Wankhede Stadium,2017
...,...,...,...,...,...,...,...,...
751,11347,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,Wankhede Stadium,2019
752,11412,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,Mumbai Indians,M. A. Chidambaram Stadium,2019
753,11413,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,Delhi Capitals,ACA-VDCA Stadium,2019
754,11414,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,ACA-VDCA Stadium,2019
755,11415,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,Mumbai Indians,Rajiv Gandhi Intl. Cricket Stadium,2019

In [235]:
match_df=match_df.merge(total_runs[['match_id','total_runs']],on='match_id')

In [236]:
match_df.columns

Index(['match_id', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'venue', 'Season_year', 'total_runs'],
      dtype='object')

In [237]:
delivery_df=delivery_df[delivery_df['inning']==2]

In [238]:
delivery_df = match_df.merge(delivery_df, on='match_id')

In [239]:
delivery_df

,match_id,team1,team2,toss_winner,toss_decision,winner,venue,Season_year,total_runs_x,inning,...,bowling_team,over,ball,batsman_runs,extra_runs,total_runs_y,player_dismissed,batsman_sr,economy,wicket_rate
0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017,207,2,...,Sunrisers Hyderabad,1,1,1,0,1,NaN,141.686664,7.634663,0.381546
1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017,207,2,...,Sunrisers Hyderabad,1,2,0,0,0,NaN,124.684685,7.634663,0.381546
2,1,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017,207,2,...,Sunrisers Hyderabad,1,3,0,0,0,NaN,124.684685,7.634663,0.381546
3,1,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017,207,2,...,Sunrisers Hyderabad,1,4,2,0,2,NaN,124.684685,7.634663,0.381546
4,1,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017,207,2,...,Sunrisers Hyderabad,1,5,4,0,4,NaN,124.684685,7.634663,0.381546
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75335,11415,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,Mumbai Indians,Rajiv Gandhi Intl. Cricket Stadium,2019,152,2,...,Mumbai Indians,20,2,1,0,1,NaN,118.442933,7.165091,0.377455
75336,11415,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,Mumbai Indians,Rajiv Gandhi Intl. Cricket Stadium,2019,152,2,...,Mumbai Indians,20,3,2,0,2,NaN,135.711374,7.165091,0.377455
75337,11415,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,Mumbai Indians,Rajiv Gandhi Intl. Cricket Stadium,2019,152,2,...,Mumbai Indians,20,4,1,0,1,SR Watson,135.711374,7.165091,0.377455
75338,11415,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,Mumbai Indians,Rajiv Gandhi Intl. Cricket Stadium,2019,152,2,...,Mumbai Indians,20,5,2,0,2,NaN,200.000000,7.165091,0.377455
75339,11415,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,Mumbai Indians,Rajiv Gandhi Intl. Cricket Stadium,2019,152,2,...,Mumbai Indians,20,6,0,0,0,SN Thakur,200.000000,7.165091,0.377455

In [240]:
delivery_df=delivery_df.rename(columns={'total_runs_x':'total_runs','total_runs_y':'runs_per_ball'})

In [241]:
delivery_df

,match_id,team1,team2,toss_winner,toss_decision,winner,venue,Season_year,total_runs,inning,...,bowling_team,over,ball,batsman_runs,extra_runs,runs_per_ball,player_dismissed,batsman_sr,economy,wicket_rate
0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017,207,2,...,Sunrisers Hyderabad,1,1,1,0,1,NaN,141.686664,7.634663,0.381546
1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017,207,2,...,Sunrisers Hyderabad,1,2,0,0,0,NaN,124.684685,7.634663,0.381546
2,1,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017,207,2,...,Sunrisers Hyderabad,1,3,0,0,0,NaN,124.684685,7.634663,0.381546
3,1,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017,207,2,...,Sunrisers Hyderabad,1,4,2,0,2,NaN,124.684685,7.634663,0.381546
4,1,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017,207,2,...,Sunrisers Hyderabad,1,5,4,0,4,NaN,124.684685,7.634663,0.381546
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75335,11415,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,Mumbai Indians,Rajiv Gandhi Intl. Cricket Stadium,2019,152,2,...,Mumbai Indians,20,2,1,0,1,NaN,118.442933,7.165091,0.377455
75336,11415,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,Mumbai Indians,Rajiv Gandhi Intl. Cricket Stadium,2019,152,2,...,Mumbai Indians,20,3,2,0,2,NaN,135.711374,7.165091,0.377455
75337,11415,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,Mumbai Indians,Rajiv Gandhi Intl. Cricket Stadium,2019,152,2,...,Mumbai Indians,20,4,1,0,1,SR Watson,135.711374,7.165091,0.377455
75338,11415,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,Mumbai Indians,Rajiv Gandhi Intl. Cricket Stadium,2019,152,2,...,Mumbai Indians,20,5,2,0,2,NaN,200.000000,7.165091,0.377455
75339,11415,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,Mumbai Indians,Rajiv Gandhi Intl. Cricket Stadium,2019,152,2,...,Mumbai Indians,20,6,0,0,0,SN Thakur,200.000000,7.165091,0.377455

In [242]:
#delivery_df['Score'] = delivery_df[['match_id','runs_per_ball']].groupby('match_id').cumsum()['runs_per_ball']
delivery_df['score']=delivery_df.groupby('match_id')['runs_per_ball'].cumsum()

In [243]:
delivery_df[['match_id','runs_per_ball','score']]

       match_id  runs_per_ball  score
0             1              1      1
1             1              0      1
2             1              0      1
3             1              2      3
4             1              4      7
...         ...            ...    ...
75335     11415              1    152
75336     11415              2    154
75337     11415              1    155
75338     11415              2    157
75339     11415              0    157

[75340 rows x 3 columns]

In [244]:
delivery_df['target_left']=(delivery_df['total_runs']+1)-(delivery_df['score'])

In [245]:
delivery_df.columns

Index(['match_id', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'venue', 'Season_year', 'total_runs', 'inning', 'batting_team',
       'bowling_team', 'over', 'ball', 'batsman_runs', 'extra_runs',
       'runs_per_ball', 'player_dismissed', 'batsman_sr', 'economy',
       'wicket_rate', 'score', 'target_left'],
      dtype='object')

In [246]:
delivery_df.drop(['team1','team2'],axis=1,inplace=True)

In [247]:
delivery_df['player_dismissed']=delivery_df['player_dismissed'].fillna('0');
delivery_df['player_dismissed']=delivery_df['player_dismissed'].apply(lambda x: x if x=='0' else '1').astype(int)

In [248]:
delivery_df[['match_id','player_dismissed']]

       match_id  player_dismissed
0             1                 0
1             1                 0
2             1                 0
3             1                 0
4             1                 0
...         ...               ...
75335     11415                 0
75336     11415                 0
75337     11415                 1
75338     11415                 0
75339     11415                 1

[75340 rows x 2 columns]

In [249]:
delivery_df['wickets']=delivery_df[['match_id','player_dismissed']].groupby('match_id').cumsum()['player_dismissed']

In [250]:
delivery_df[['match_id','wickets']]

       match_id  wickets
0             1        0
1             1        0
2             1        0
3             1        0
4             1        0
...         ...      ...
75335     11415        5
75336     11415        5
75337     11415        6
75338     11415        6
75339     11415        7

[75340 rows x 2 columns]

In [251]:
delivery_df['wickets']=10-delivery_df['wickets']

In [252]:
delivery_df[['match_id','wickets']]

       match_id  wickets
0             1       10
1             1       10
2             1       10
3             1       10
4             1       10
...         ...      ...
75335     11415        5
75336     11415        5
75337     11415        4
75338     11415        4
75339     11415        3

[75340 rows x 2 columns]

In [253]:
delivery_df['remaining_balls']=120-((delivery_df['over']-1)*6+delivery_df['ball'])

In [254]:
delivery_df['CRR']=delivery_df['score']/((delivery_df['over']-1)+((delivery_df['ball'])/6))

In [255]:
delivery_df[['match_id','CRR']]

       match_id       CRR
0             1  6.000000
1             1  3.000000
2             1  2.000000
3             1  4.500000
4             1  8.400000
...         ...       ...
75335     11415  7.862069
75336     11415  7.897436
75337     11415  7.881356
75338     11415  7.915966
75339     11415  7.850000

[75340 rows x 2 columns]

In [256]:
delivery_df['RRR']=(delivery_df['target_left'])*6/delivery_df['remaining_balls']

In [257]:
delivery_df[['match_id','RRR']]

       match_id        RRR
0             1  10.436975
1             1  10.525424
2             1  10.615385
3             1  10.603448
4             1  10.486957
...         ...        ...
75335     11415   1.500000
75336     11415  -2.000000
75337     11415  -6.000000
75338     11415 -24.000000
75339     11415       -inf

[75340 rows x 2 columns]

In [258]:
delivery_df[delivery_df['remaining_balls']==0]

,match_id,toss_winner,toss_decision,winner,venue,Season_year,total_runs,inning,batting_team,bowling_team,...,player_dismissed,batsman_sr,economy,wicket_rate,score,target_left,wickets,remaining_balls,CRR,RRR
342,5,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,M Chinnaswamy Stadium,2017,157,2,Delhi Capitals,Royal Challengers Bangalore,...,0,87.365591,8.145455,0.327273,142,16,1,0,7.10,inf
1113,14,Sunrisers Hyderabad,field,Kolkata Knight Riders,Eden Gardens,2017,172,2,Sunrisers Hyderabad,Kolkata Knight Riders,...,0,116.286389,8.738155,0.306733,155,18,4,0,7.75,inf
1234,15,Delhi Capitals,bat,Delhi Capitals,Feroz Shah Kotla,2017,188,2,Kings XI Punjab,Delhi Capitals,...,1,125.247525,8.120158,0.341502,137,52,1,0,6.85,inf
1606,19,Kings XI Punjab,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017,159,2,Kings XI Punjab,Sunrisers Hyderabad,...,1,94.736842,8.521277,0.300000,154,6,0,0,7.70,inf
1732,20,Gujarat Titans,field,Royal Challengers Bangalore,Saurashtra Cricket Association Stadium,2017,213,2,Gujarat Titans,Royal Challengers Bangalore,...,0,93.750000,10.892308,0.184615,192,22,3,0,9.60,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73947,11338,Mumbai Indians,field,Kolkata Knight Riders,Eden Gardens,2019,241,2,Mumbai Indians,Kolkata Knight Riders,...,0,76.923077,7.942185,0.302521,204,38,3,0,10.20,inf
74074,11339,Kings XI Punjab,field,Sunrisers Hyderabad,Rajiv Gandhi Intl. Cricket Stadium,2019,232,2,Kings XI Punjab,Sunrisers Hyderabad,...,0,57.142857,8.309434,0.294340,174,59,2,0,8.70,inf
74314,11342,Mumbai Indians,bat,Mumbai Indians,Wankhede Stadium,2019,170,2,Sunrisers Hyderabad,Mumbai Indians,...,0,121.108179,9.055427,0.304850,165,6,4,0,8.25,inf
75099,11413,Delhi Capitals,field,Delhi Capitals,ACA-VDCA Stadium,2019,171,2,Delhi Capitals,Sunrisers Hyderabad,...,0,84.615385,8.738589,0.497925,170,2,3,0,8.50,inf
75339,11415,Mumbai Indians,bat,Mumbai Indians,Rajiv Gandhi Intl. Cricket Stadium,2019,152,2,Chennai Super Kings,Mumbai Indians,...,1,200.000000,7.165091,0.377455,157,-4,3,0,7.85,-inf

In [259]:
delivery_df.shape

(75340, 25)

In [260]:
delivery_df=delivery_df[delivery_df['remaining_balls']!=0]

In [261]:
delivery_df.shape

(75092, 25)

In [262]:
delivery_df

,match_id,toss_winner,toss_decision,winner,venue,Season_year,total_runs,inning,batting_team,bowling_team,...,player_dismissed,batsman_sr,economy,wicket_rate,score,target_left,wickets,remaining_balls,CRR,RRR
0,1,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,...,0,141.686664,7.634663,0.381546,1,207,10,119,6.000000,10.436975
1,1,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,...,0,124.684685,7.634663,0.381546,1,207,10,118,3.000000,10.525424
2,1,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,...,0,124.684685,7.634663,0.381546,1,207,10,117,2.000000,10.615385
3,1,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,...,0,124.684685,7.634663,0.381546,3,205,10,116,4.500000,10.603448
4,1,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",2017,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,...,0,124.684685,7.634663,0.381546,7,201,10,115,8.400000,10.486957
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75334,11415,Mumbai Indians,bat,Mumbai Indians,Rajiv Gandhi Intl. Cricket Stadium,2019,152,2,Chennai Super Kings,Mumbai Indians,...,0,135.711374,7.165091,0.377455,151,2,5,5,7.878261,2.400000
75335,11415,Mumbai Indians,bat,Mumbai Indians,Rajiv Gandhi Intl. Cricket Stadium,2019,152,2,Chennai Super Kings,Mumbai Indians,...,0,118.442933,7.165091,0.377455,152,1,5,4,7.862069,1.500000
75336,11415,Mumbai Indians,bat,Mumbai Indians,Rajiv Gandhi Intl. Cricket Stadium,2019,152,2,Chennai Super Kings,Mumbai Indians,...,0,135.711374,7.165091,0.377455,154,-1,5,3,7.897436,-2.000000
75337,11415,Mumbai Indians,bat,Mumbai Indians,Rajiv Gandhi Intl. Cricket Stadium,2019,152,2,Chennai Super Kings,Mumbai Indians,...,1,135.711374,7.165091,0.377455,155,-2,4,2,7.881356,-6.000000
75338,11415,Mumbai Indians,bat,Mumbai Indians,Rajiv Gandhi Intl. Cricket Stadium,2019,152,2,Chennai Super Kings,Mumbai Indians,...,0,200.000000,7.165091,0.377455,157,-4,4,1,7.915966,-24.000000

In [263]:
delivery_df.isnull().sum()

match_id             0
toss_winner          0
toss_decision        0
winner              27
venue                0
Season_year          0
total_runs           0
inning               0
batting_team         0
bowling_team         0
over                 0
ball                 0
batsman_runs         0
extra_runs           0
runs_per_ball        0
player_dismissed     0
batsman_sr           0
economy              0
wicket_rate          0
score                0
target_left          0
wickets              0
remaining_balls      0
CRR                  0
RRR                  0
dtype: int64

In [264]:
delivery_df['result']=(delivery_df['batting_team']== delivery_df['winner']).astype(int)

C:\Users\abhis\AppData\Local\Temp\ipykernel_29356\1873404456.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['result']=(delivery_df['batting_team']== delivery_df['winner']).astype(int)

In [265]:
delivery_df['result'].value_counts()

result
1    40344
0    34748
Name: count, dtype: int64

In [266]:
delivery_df.isnull().sum()

match_id             0
toss_winner          0
toss_decision        0
winner              27
venue                0
Season_year          0
total_runs           0
inning               0
batting_team         0
bowling_team         0
over                 0
ball                 0
batsman_runs         0
extra_runs           0
runs_per_ball        0
player_dismissed     0
batsman_sr           0
economy              0
wicket_rate          0
score                0
target_left          0
wickets              0
remaining_balls      0
CRR                  0
RRR                  0
result               0
dtype: int64

In [267]:
delivery_df.dropna(inplace=True)

C:\Users\abhis\AppData\Local\Temp\ipykernel_29356\4020265422.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df.dropna(inplace=True)

In [268]:
delivery_df.columns

Index(['match_id', 'toss_winner', 'toss_decision', 'winner', 'venue',
       'Season_year', 'total_runs', 'inning', 'batting_team', 'bowling_team',
       'over', 'ball', 'batsman_runs', 'extra_runs', 'runs_per_ball',
       'player_dismissed', 'batsman_sr', 'economy', 'wicket_rate', 'score',
       'target_left', 'wickets', 'remaining_balls', 'CRR', 'RRR', 'result'],
      dtype='object')

In [269]:
Model_df=delivery_df[['toss_winner','toss_decision','venue','Season_year','batting_team','bowling_team','batsman_sr','economy','wicket_rate','score','target_left','wickets','remaining_balls','CRR','RRR','result']]

In [270]:
Model_df

,toss_winner,toss_decision,venue,Season_year,batting_team,bowling_team,batsman_sr,economy,wicket_rate,score,target_left,wickets,remaining_balls,CRR,RRR,result
0,Royal Challengers Bangalore,field,"Rajiv Gandhi International Stadium, Uppal",2017,Royal Challengers Bangalore,Sunrisers Hyderabad,141.686664,7.634663,0.381546,1,207,10,119,6.000000,10.436975,0
1,Royal Challengers Bangalore,field,"Rajiv Gandhi International Stadium, Uppal",2017,Royal Challengers Bangalore,Sunrisers Hyderabad,124.684685,7.634663,0.381546,1,207,10,118,3.000000,10.525424,0
2,Royal Challengers Bangalore,field,"Rajiv Gandhi International Stadium, Uppal",2017,Royal Challengers Bangalore,Sunrisers Hyderabad,124.684685,7.634663,0.381546,1,207,10,117,2.000000,10.615385,0
3,Royal Challengers Bangalore,field,"Rajiv Gandhi International Stadium, Uppal",2017,Royal Challengers Bangalore,Sunrisers Hyderabad,124.684685,7.634663,0.381546,3,205,10,116,4.500000,10.603448,0
4,Royal Challengers Bangalore,field,"Rajiv Gandhi International Stadium, Uppal",2017,Royal Challengers Bangalore,Sunrisers Hyderabad,124.684685,7.634663,0.381546,7,201,10,115,8.400000,10.486957,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75334,Mumbai Indians,bat,Rajiv Gandhi Intl. Cricket Stadium,2019,Chennai Super Kings,Mumbai Indians,135.711374,7.165091,0.377455,151,2,5,5,7.878261,2.400000,0
75335,Mumbai Indians,bat,Rajiv Gandhi Intl. Cricket Stadium,2019,Chennai Super Kings,Mumbai Indians,118.442933,7.165091,0.377455,152,1,5,4,7.862069,1.500000,0
75336,Mumbai Indians,bat,Rajiv Gandhi Intl. Cricket Stadium,2019,Chennai Super Kings,Mumbai Indians,135.711374,7.165091,0.377455,154,-1,5,3,7.897436,-2.000000,0
75337,Mumbai Indians,bat,Rajiv Gandhi Intl. Cricket Stadium,2019,Chennai Super Kings,Mumbai Indians,135.711374,7.165091,0.377455,155,-2,4,2,7.881356,-6.000000,0
75338,Mumbai Indians,bat,Rajiv Gandhi Intl. Cricket Stadium,2019,Chennai Super Kings,Mumbai Indians,200.000000,7.165091,0.377455,157,-4,4,1,7.915966,-24.000000,0

In [271]:
Model_df.shape

(75065, 16)

In [272]:
Model_df=Model_df.sample(Model_df.shape[0])

In [273]:
Model_df

,toss_winner,toss_decision,venue,Season_year,batting_team,bowling_team,batsman_sr,economy,wicket_rate,score,target_left,wickets,remaining_balls,CRR,RRR,result
58688,Royal Challengers Bangalore,field,"Rajiv Gandhi International Stadium, Uppal",2016,Royal Challengers Bangalore,Sunrisers Hyderabad,147.965430,8.247325,0.271106,109,86,7,41,8.278481,12.585366,0
70012,Rajasthan Royals,field,Sawai Mansingh Stadium,2019,Rajasthan Royals,Royal Challengers Bangalore,149.390919,7.832776,0.337793,110,55,9,47,9.041096,7.021277,1
8657,Kolkata Knight Riders,bat,Eden Gardens,2008,Delhi Capitals,Kolkata Knight Riders,123.397705,7.533569,0.261484,43,91,6,75,5.733333,7.280000,0
56719,Sunrisers Hyderabad,field,M Chinnaswamy Stadium,2016,Sunrisers Hyderabad,Royal Challengers Bangalore,122.990127,7.825683,0.300155,83,145,9,71,10.163265,12.253521,0
37873,Kolkata Knight Riders,field,"Punjab Cricket Association Stadium, Mohali",2013,Kolkata Knight Riders,Kings XI Punjab,118.593750,8.310984,0.333809,62,96,8,76,8.454545,7.578947,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42794,Chennai Super Kings,bat,Feroz Shah Kotla,2013,Mumbai Indians,Chennai Super Kings,143.515541,7.700943,0.288679,96,97,7,56,9.000000,10.392857,0
50369,Kings XI Punjab,field,Maharashtra Cricket Association Stadium,2015,Kings XI Punjab,Rajasthan Royals,120.246660,8.116461,0.305711,47,116,7,86,8.294118,8.093023,0
42630,Kolkata Knight Riders,bat,"Rajiv Gandhi International Stadium, Uppal",2013,Sunrisers Hyderabad,Kolkata Knight Riders,118.419800,7.407883,0.208983,17,114,10,102,5.666667,6.705882,1
10238,Sunrisers Hyderabad,field,M Chinnaswamy Stadium,2008,Sunrisers Hyderabad,Royal Challengers Bangalore,129.423347,6.646999,0.299084,62,95,8,60,6.200000,9.500000,0
21806,Kings XI Punjab,bat,Sawai Mansingh Stadium,2010,Rajasthan Royals,Kings XI Punjab,139.305556,8.478873,0.366197,120,34,9,50,10.285714,4.080000,1

In [274]:
X=Model_df.iloc[:,:-1]
y=Model_df.iloc[:,-1]

In [275]:
X.head()

,toss_winner,toss_decision,venue,Season_year,batting_team,bowling_team,batsman_sr,economy,wicket_rate,score,target_left,wickets,remaining_balls,CRR,RRR
58688,Royal Challengers Bangalore,field,"Rajiv Gandhi International Stadium, Uppal",2016,Royal Challengers Bangalore,Sunrisers Hyderabad,147.965430,8.247325,0.271106,109,86,7,41,8.278481,12.585366
70012,Rajasthan Royals,field,Sawai Mansingh Stadium,2019,Rajasthan Royals,Royal Challengers Bangalore,149.390919,7.832776,0.337793,110,55,9,47,9.041096,7.021277
8657,Kolkata Knight Riders,bat,Eden Gardens,2008,Delhi Capitals,Kolkata Knight Riders,123.397705,7.533569,0.261484,43,91,6,75,5.733333,7.280000
56719,Sunrisers Hyderabad,field,M Chinnaswamy Stadium,2016,Sunrisers Hyderabad,Royal Challengers Bangalore,122.990127,7.825683,0.300155,83,145,9,71,10.163265,12.253521
37873,Kolkata Knight Riders,field,"Punjab Cricket Association Stadium, Mohali",2013,Kolkata Knight Riders,Kings XI Punjab,118.593750,8.310984,0.333809,62,96,8,76,8.454545,7.578947

In [276]:
y.head()

58688    0
70012    1
8657     0
56719    0
37873    0
Name: result, dtype: int64

In [277]:
from sklearn.model_selection import train_test_split

In [278]:
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [279]:
X_train

,toss_winner,toss_decision,venue,Season_year,batting_team,bowling_team,batsman_sr,economy,wicket_rate,score,target_left,wickets,remaining_balls,CRR,RRR
34223,Chennai Super Kings,field,Sawai Mansingh Stadium,2012,Chennai Super Kings,Rajasthan Royals,124.978467,7.078431,0.215686,56,71,8,56,5.250000,7.607143
66128,Kolkata Knight Riders,field,Eden Gardens,2018,Kolkata Knight Riders,Mumbai Indians,110.714286,7.663653,0.300181,84,134,3,47,6.904110,17.106383
70683,Delhi Capitals,field,M. Chinnaswamy Stadium,2019,Delhi Capitals,Royal Challengers Bangalore,125.589971,7.832776,0.337793,41,114,9,96,10.250000,7.125000
51338,Kings XI Punjab,bat,Maharashtra Cricket Association Stadium,2015,Delhi Capitals,Kings XI Punjab,123.305358,8.194514,0.279302,45,121,9,88,8.437500,8.250000
25459,Chennai Super Kings,bat,"MA Chidambaram Stadium, Chepauk",2011,Royal Challengers Bangalore,Chennai Super Kings,129.044784,8.012232,0.293578,47,137,7,74,6.130435,11.108108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17935,Sunrisers Hyderabad,bat,"MA Chidambaram Stadium, Chepauk",2010,Chennai Super Kings,Sunrisers Hyderabad,137.280059,7.429199,0.299671,90,101,5,41,6.835443,14.780488
41055,Sunrisers Hyderabad,field,"Rajiv Gandhi International Stadium, Uppal",2013,Sunrisers Hyderabad,Chennai Super Kings,118.419800,8.236842,0.210526,38,186,9,92,8.142857,12.130435
33145,Rajasthan Royals,bat,Sawai Mansingh Stadium,2012,Delhi Capitals,Rajasthan Royals,133.078101,9.106109,0.212219,77,65,9,75,10.266667,5.200000
35213,Delhi Capitals,field,Feroz Shah Kotla,2012,Delhi Capitals,Royal Challengers Bangalore,96.258503,7.601914,0.310048,39,177,9,96,9.750000,11.062500
67250,Sunrisers Hyderabad,field,M Chinnaswamy Stadium,2018,Sunrisers Hyderabad,Royal Challengers Bangalore,121.108179,7.832776,0.337793,161,62,8,26,10.276596,14.307692

In [280]:
X_test

,toss_winner,toss_decision,venue,Season_year,batting_team,bowling_team,batsman_sr,economy,wicket_rate,score,target_left,wickets,remaining_balls,CRR,RRR
63836,Mumbai Indians,bat,Sawai Mansingh Stadium,2018,Rajasthan Royals,Mumbai Indians,124.436090,7.663653,0.300181,102,71,8,45,8.160000,9.466667
49551,Mumbai Indians,field,Wankhede Stadium,2014,Mumbai Indians,Rajasthan Royals,129.423347,7.887273,0.381818,73,117,7,82,11.526316,8.560976
66401,Kings XI Punjab,field,Holkar Cricket Stadium,2018,Kings XI Punjab,Kolkata Knight Riders,141.686664,6.879203,0.318804,2,249,10,118,6.000000,12.661017
45939,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,2014,Royal Challengers Bangalore,Sunrisers Hyderabad,125.833333,8.058309,0.320700,95,61,6,34,6.627907,10.764706
43195,Mumbai Indians,bat,Eden Gardens,2013,Chennai Super Kings,Mumbai Indians,109.259259,8.293059,0.318766,99,50,1,13,5.551402,23.076923
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13976,Kings XI Punjab,field,Kingsmead,2009,Kings XI Punjab,Rajasthan Royals,125.833333,6.626866,0.268657,53,159,5,59,5.213115,16.169492
24849,Delhi Capitals,bat,Sawai Mansingh Stadium,2011,Rajasthan Royals,Delhi Capitals,80.327869,7.533569,0.261484,26,126,10,103,9.176471,7.339806
53445,Delhi Capitals,field,Feroz Shah Kotla,2015,Delhi Capitals,Kings XI Punjab,125.589971,8.612903,0.258065,50,69,10,78,7.142857,5.307692
26684,Delhi Capitals,field,Feroz Shah Kotla,2011,Delhi Capitals,Kolkata Knight Riders,114.842767,7.325843,0.299625,86,63,4,30,5.733333,12.600000
53268,Kolkata Knight Riders,bat,Eden Gardens,2015,Delhi Capitals,Kolkata Knight Riders,113.801453,8.908397,0.337786,138,34,5,9,7.459459,22.666667

In [281]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60052 entries, 34223 to 67250
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   toss_winner      60052 non-null  object
 1   toss_decision    60052 non-null  object
 2   venue            60052 non-null  object
 3   Season_year      60052 non-null  int64
 4   batting_team     60052 non-null  object
 5   bowling_team     60052 non-null  object
 6   batsman_sr       60052 non-null  float64
 7   economy          60052 non-null  float64
 8   wicket_rate      60052 non-null  float64
 9   score            60052 non-null  int64
 10  target_left      60052 non-null  int64
 11  wickets          60052 non-null  int64
 12  remaining_balls  60052 non-null  int64
 13  CRR              60052 non-null  float64
 14  RRR              60052 non-null  float64
dtypes: float64(5), int64(5), object(5)
memory usage: 7.3+ MB

In [282]:
X_train[['toss_winner','toss_decision','venue','batting_team','bowling_team',]].head()

,toss_winner,toss_decision,venue,batting_team,bowling_team
34223,Chennai Super Kings,field,Sawai Mansingh Stadium,Chennai Super Kings,Rajasthan Royals
66128,Kolkata Knight Riders,field,Eden Gardens,Kolkata Knight Riders,Mumbai Indians
70683,Delhi Capitals,field,M. Chinnaswamy Stadium,Delhi Capitals,Royal Challengers Bangalore
51338,Kings XI Punjab,bat,Maharashtra Cricket Association Stadium,Delhi Capitals,Kings XI Punjab
25459,Chennai Super Kings,bat,"MA Chidambaram Stadium, Chepauk",Royal Challengers Bangalore,Chennai Super Kings

In [283]:
Y_train.head()

34223    1
66128    0
70683    1
51338    1
25459    0
Name: result, dtype: int64

In [284]:
Y_test.head()

63836    1
49551    1
66401    0
45939    1
43195    0
Name: result, dtype: int64

In [285]:
categorical_cols = [
    'toss_winner', 'toss_decision', 'venue', 'batting_team', 'bowling_team'
]

In [286]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [287]:
preprocessing=ColumnTransformer([
    ('transform',
     OneHotEncoder(sparse_output=False,drop='first',handle_unknown='ignore'),
     categorical_cols)],remainder='passthrough')

In [288]:
preprocessing

ColumnTransformer(remainder='passthrough',
                  transformers=[('transform',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 ['toss_winner', 'toss_decision', 'venue',
                                  'batting_team', 'bowling_team'])])

In [289]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [290]:
pipe=Pipeline(
       steps=[('preprocess',preprocessing),
             ('model',LogisticRegression(solver='liblinear'))]
             )

In [291]:
pipe.fit(X_train,Y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('transform',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['toss_winner',
                                                   'toss_decision', 'venue',
                                                   'batting_team',
                                                   'bowling_team'])])),
                ('model', LogisticRegression(solver='liblinear'))])

In [292]:
prediction=pipe.predict(X_test)

In [293]:
prediction

array([1, 0, 0, ..., 1, 0, 0], shape=(15013,))

In [294]:
from sklearn.metrics import accuracy_score

In [295]:
accuracy_score(Y_test,prediction)

0.814094451475388

In [296]:
pipe.predict_proba(X_test)[:5]

array([[0.18317006, 0.81682994],
       [0.54761405, 0.45238595],
       [0.91814735, 0.08185265],
       [0.53256717, 0.46743283],
       [0.98423383, 0.01576617]])

In [297]:
prediction_train=pipe.predict(X_train)
prediction_train

array([1, 0, 1, ..., 1, 0, 1], shape=(60052,))

In [298]:
accuracy_score(Y_train,prediction_train)

0.8140611470059282

In [299]:
accuracy_score(Y_test,prediction)

0.814094451475388

In [300]:
batsman_stat=batsman_stat.set_index('batsman')

In [301]:
batsman_stat

                runs  balls_faced  batsman_sr
batsman
A Ashish Reddy   254          177  143.502825
A Chandila         4            7   57.142857
A Chopra          53           75   70.666667
A Choudhary       25           20  125.000000
A Dananjaya        4            5   80.000000
...              ...          ...         ...
YV Takawale      192          183  104.918033
Yashpal Singh     47           67   70.149254
Younis Khan        3            7   42.857143
Yuvraj Singh    2114         1680  125.833333
Z Khan           117          141   82.978723

[493 rows x 3 columns]

In [302]:
bowlers_stat=bowlers_stat.set_index('bowler')

In [303]:
bowlers_stat

,run_conceded,balls_bowled,wickets_took,economy,wicket_rate
bowler,,,,,
A Ashish Reddy,315,215,15,8.790698,0.418605
A Chandila,209,198,7,6.333333,0.212121
A Choudhary,144,108,5,8.000000,0.277778
A Dananjaya,48,25,0,11.520000,0.000000
A Flintoff,106,66,2,9.636364,0.181818
...,...,...,...,...,...
YA Abdulla,311,222,15,8.405405,0.405405
YK Pathan,1347,1091,38,7.407883,0.208983
YS Chahal,2342,1794,101,7.832776,0.337793
Yuvraj Singh,737,568,24,7.785211,0.253521
Z Khan,2648,2090,108,7.601914,0.310048

In [304]:
batsman_stat.loc['A Chopra','batsman_sr']

np.float64(70.66666666666667)

In [305]:
bowlers_stat.loc['Z Khan','economy']

np.float64(7.601913875598086)

In [306]:
X_train.columns

Index(['toss_winner', 'toss_decision', 'venue', 'Season_year', 'batting_team',
       'bowling_team', 'batsman_sr', 'economy', 'wicket_rate', 'score',
       'target_left', 'wickets', 'remaining_balls', 'CRR', 'RRR'],
      dtype='object')

In [307]:
import pickle as pkl

In [308]:
pkl.dump(pipe,open('Model.pkl','wb'))

In [309]:
pkl.dump(batsman_stat,open('batsman_stat.pkl','wb'))

In [310]:
pkl.dump(bowlers_stat,open('bowlers_stat.pkl','wb'))

In [311]:
Toss_decision=list(Model_df['toss_decision'].unique())

In [312]:
list(batsman_stat.index)

['A Ashish Reddy',
 'A Chandila',
 'A Chopra',
 'A Choudhary',
 'A Dananjaya',
 'A Flintoff',
 'A Hales',
 'A Joseph',
 'A Kumble',
 'A Mishra',
 'A Mithun',
 'A Mukund',
 'A Nehra',
 'A Singh',
 'A Symonds',
 'A Turner',
 'A Uniyal',
 'AA Bilakhia',
 'AA Chavan',
 'AA Jhunjhunwala',
 'AA Noffke',
 'AB Agarkar',
 'AB Barath',
 'AB Dinda',
 'AB McDonald',
 'AB de Villiers',
 'AC Blizzard',
 'AC Gilchrist',
 'AC Voges',
 'AD Mascarenhas',
 'AD Mathews',
 'AD Nath',
 'AD Russell',
 'AF Milne',
 'AG Murtaza',
 'AG Paunikar',
 'AJ Finch',
 'AJ Tye',
 'AL Menaria',
 'AM Nayar',
 'AM Rahane',
 'AN Ahmed',
 'AN Ghosh',
 'AP Dole',
 'AP Tare',
 'AR Bawne',
 'AR Patel',
 'AS Rajpoot',
 'AS Raut',
 'AS Yadav',
 'AT Rayudu',
 'AUK Pathan',
 'Abdur Razzak',
 'Anirudh Singh',
 'Ankit Sharma',
 'Ankit Soni',
 'Anureet Singh',
 'Avesh Khan',
 'Azhar Mahmood',
 'B Akhil',
 'B Chipli',
 'B Kumar',
 'B Laughlin',
 'B Lee',
 'B Stanlake',
 'B Sumanth',
 'BA Bhatt',
 'BA Stokes',
 'BAW Mendis',
 'BB McCullum',
 'BB Samantray',
 'BB Sran',
 'BCJ Cutting',
 'BE Hendricks',
 'BJ Haddin',
 'BJ Hodge',
 'BJ Rohrer',
 'BMAJ Mendis',
 'BR Dunk',
 'Basil Thampi',
 'Bipul Sharma',
 'C Ingram',
 'C Madan',
 'C Munro',
 'C Nanda',
 'C de Grandhomme',
 'CA Ingram',
 'CA Lynn',
 'CA Pujara',
 'CH Gayle',
 'CH Morris',
 'CJ Anderson',
 'CJ Jordan',
 'CJ McKay',
 'CK Kapugedera',
 'CK Langeveldt',
 'CL White',
 'CM Gautam',
 'CR Brathwaite',
 'CR Woakes',
 'CRD Fernando',
 'D Kalyankrishna',
 'D Salunkhe',
 'D Shorey',
 'D Short',
 'D Wiese',
 'D du Preez',
 'DA Miller',
 'DA Warner',
 'DAJ Bracewell',
 'DB Das',
 'DB Ravi Teja',
 'DE Bollinger',
 'DH Yagnik',
 'DJ Bravo',
 'DJ Harris',
 'DJ Hooda',
 'DJ Hussey',
 'DJ Jacobs',
 'DJ Muthuswami',
 'DJ Thornely',
 'DJG Sammy',
 'DL Chahar',
 'DL Vettori',
 'DNT Zoysa',
 'DP Nannes',
 'DP Vijaykumar',
 'DPMD Jayawardene',
 'DR Martyn',
 'DR Smith',
 'DS Kulkarni',
 'DS Lehmann',
 'DT Christian',
 'DT Patil',
 'DW Steyn',
 'E Lewis',
 'EJG Morgan',
 'ER Dwivedi',
 'F Behardien',
 'F du Plessis',
 'FH Edwards',
 'FY Fazal',
 'G Gambhir',
 'GB Hogg',
 'GC Smith',
 'GD McGrath',
 'GH Vihari',
 'GJ Bailey',
 'GJ Maxwell',
 'GR Napier',
 'Gurkeerat Singh',
 'H Brar',
 'H Das',
 'H Gurney',
 'H Klaasen',
 'H Vihari',
 'H Viljoen',
 'HH Gibbs',
 'HH Pandya',
 'HM Amla',
 'HV Patel',
 'Harbhajan Singh',
 'Harmeet Singh',
 'I Malhotra',
 'I Sharma',
 'I Sodhi',
 'IK Pathan',
 'IR Jaggi',
 'Imran Tahir',
 'Iqbal Abdulla',
 'Ishan Kishan',
 'J Archer',
 'J Arunkumar',
 'J Bairstow',
 'J Botha',
 'J Denly',
 'J Searles',
 'J Suchith',
 'J Syed Mohammad',
 'J Theron',
 'J Yadav',
 'JA Morkel',
 'JC Buttler',
 'JD Ryder',
 'JD Unadkat',
 'JDP Oram',
 'JDS Neesham',
 'JEC Franklin',
 'JH Kallis',
 'JJ Bumrah',
 'JJ Roy',
 'JJ van der Wath',
 'JM Kemp',
 'JO Holder',
 'JP Duminy',
 'JP Faulkner',
 'JR Hopes',
 'Jaskaran Singh',
 'Joginder Sharma',
 'K Ahmed',
 'K Goel',
 'K Gowtham',
 'K Paul',
 'K Rabada',
 'KA Pollard',
 'KAJ Roach',
 'KB Arun Karthik',
 'KC Cariappa',
 'KC Sangakkara',
 'KD Karthik',
 'KH Pandya',
 'KJ Abbott',
 'KK Cooper',
 'KK Nair',
 'KL Rahul',
 'KM Jadhav',
 'KMDN Kulasekara',
 'KP Appanna',
 'KP Pietersen',
 'KS Williamson',
 'KV Sharma',
 'KW Richardson',
 'Kamran Akmal',
 'Kamran Khan',
 'Karanveer Singh',
 'Kuldeep Yadav',
 'L Ablish',
 'L Balaji',
 'L Livingstone',
 'L Plunkett',
 'L Ronchi',
 'LA Carseldine',
 'LA Pomersbach',
 'LMP Simmons',
 'LPC Silva',
 'LR Shukla',
 'LRPL Taylor',
 'M Ali',
 'M Ashwin',
 'M Kaif',
 'M Kartik',
 'M Lomror',
 'M Manhas',
 'M Markande',
 'M Morkel',
 'M Muralitharan',
 'M Ntini',
 'M Rawat',
 'M Santner',
 'M Ur Rahman',
 'M Vijay',
 'M Vohra',
 'M Wood',
 'M de Lange',
 'MA Agarwal',
 'MA Khote',
 'MA Starc',
 'MC Henriques',
 'MC Juneja',
 'MD Mishra',
 'MDKJ Perera',
 'MEK Hussey',
 'MF Maharoof',
 'MG Johnson',
 'MJ Guptill',
 'MJ Lumb',
 'MJ McClenaghan',
 'MK Pandey',
 'MK Tiwary',
 'ML Hayden',
 'MM Patel',
 'MM Sharma',
 'MN Samuels',
 'MN van Wyk',
 'MP Stoinis',
 'MR Marsh',
 'MS Bisla',
 'MS Dhoni',
 'MS Gony',
 'MS Wade',
 'MV Boucher',
 'Mandeep Singh',
 'Mashrafe Mortaza',
 'Misbah-ul-Haq',
 'Mohammad Ashraful',
 'Mohammad Asif',
 'Mohammad Hafeez',
 'Mohammad Nabi',
 'Mohammed Shami',
 'Mohammed Siraj',
 'Mustafizur Rahman',
 'N Naik',
 'N Pooran',
 'N Rana',
 'N Saini',
 'NJ Maddinson',
 'NLTC Perera',
 'NM Coulter-Nile',
 'NS Naik',
 'NV Ojha',
 'Niraj Patel',
 'OA Shah',
 'P Awana',
 'P Chopra',
 'P Dogra',
 'P Krishna',
 'P Kumar',
 'P Negi',
 'P Parameswaran',
 'P R Barman',
 'P Raj',
 'P Sahu',
 'P Shaw',
 'PA Patel',
 'PA Reddy',
 'PC Valthaty',
 'PD Collingwood',
 'PJ Cummins',
 'PJ Sangwan',
 'PM Sarvesh Kumar',
 'PP Chawla',
 'PP Ojha',
 'PR Shah',
 'PV Tambe',
 'Pankaj Singh',
 'Parvez Rasool',
 'Q de Kock',
 'R Ashwin',
 'R Bhatia',
 'R Bhui',
 'R Bishnoi',
 'R Dhawan',
 'R Dravid',
 'R McLaren',
 'R Ninan',
 'R Parag',
 'R Rampaul',
 'R Salam',
 'R Sathish',
 'R Sharma',
 'R Shukla',
 'R Singh',
 'R Tewatia',
 'R Vinay Kumar',
 'RA Jadeja',
 'RA Tripathi',
 'RD Chahar',
 'RE Levi',
 'RE van der Merwe',
 'RG More',
 'RG Sharma',
 'RJ Harris',
 'RJ Peterson',
 'RJ Quiney',
 'RN ten Doeschate',
 'RP Singh',
 'RR Bhatkal',
 'RR Pant',
 'RR Powar',
 'RR Raje',
 'RR Rossouw',
 'RR Sarwan',
 'RS Bopara',
 'RS Gavaskar',
 'RS Sodhi',
 'RT Ponting',
 'RV Uthappa',
 'Rashid Khan',
 'S Anirudha',
 'S Aravind',
 'S Badree',
 'S Badrinath',
 'S Chanderpaul',
 'S Curran',
 'S Dhawan',
 'S Dube',
 'S Gill',
 'S Gopal',
 'S Hetmyer',
 'S Kaul',
 'S Kaushik',
 'S Ladda',
 'S Lamichhane',
 'S Mavi',
 'S Nadeem',
 'S Narwal',
 'S Rana',
 'S Randiv',
 'S Rutherford',
 'S Sharma',
 'S Singh',
 'S Sohal',
 'S Sreesanth',
 'S Sriram',
 'S Tyagi',
 'S Vidyut',
 'SA Abbott',
 'SA Asnodkar',
 'SA Yadav',
 'SB Bangar',
 'SB Jakati',
 'SB Joshi',
 'SB Styris',
 'SC Ganguly',
 'SD Chitnis',
 'SD Lad',
 'SE Bond',
 'SE Marsh',
 'SJ Srivastava',
 'SK Raina',
 'SK Trivedi',
 'SK Warne',
 'SL Malinga',
 'SM Harwood',
 'SM Katich',
 'SM Pollock',
 'SMSM Senanayake',
 'SN Khan',
 'SN Thakur',
 'SP Fleming',
 'SP Goswami',
 'SP Jackson',
 'SP Narine',
 'SPD Smith',
 'SR Tendulkar',
 'SR Watson',
 'SS Iyer',
 'SS Shaikh',
 'SS Tiwary',
 'ST Jayasuriya',
 'STR Binny',
 'SV Samson',
 'SW Billings',
 'SW Tait',
 'Sachin Baby',
 'Salman Butt',
 'Sandeep Sharma',
 'Shahid Afridi',
 'Shakib Al Hasan',
 'Shivam Sharma',
 'Shoaib Ahmed',
 'Shoaib Akhtar',
 'Shoaib Malik',
 'Sohail Tanvir',
 'Sunny Gupta',
 'Sunny Singh',
 'Swapnil Singh',
 'T Curran',
 'T Henderson',
 'T Kohli',
 'T Taibu',
 'T Thushara',
 'TA Boult',
 'TG Southee',
 'TL Suman',
 'TM Dilshan',
 'TM Head',
 'TM Srivastava',
 'TR Birt',
 'TS Mills',
 'U Kaul',
 'UBT Chand',
 'UT Yadav',
 'Umar Gul',
 'V Kohli',
 'V Pratap Singh',
 'V Sehwag',
 'V Shankar',
 'VH Zol',
 'VR Aaron',
 'VRV Singh',
 'VS Malik',
 'VS Yeligati',
 'VVS Laxman',
 'VY Mahesh',
 'Vishnu Vinod',
 'W Jaffer',
 'WA Mota',
 'WD Parnell',
 'WP Saha',
 'WPUJC Vaas',
 'Washington Sundar',
 'X Thalaivan Sargunam',
 'Y Nagar',
 'Y Venugopal Rao',
 'YA Abdulla',
 'YK Pathan',
 'YS Chahal',
 'YV Takawale',
 'Yashpal Singh',
 'Younis Khan',
 'Yuvraj Singh',
 'Z Khan']

In [313]:
Toss_decision

['field', 'bat']

In [314]:
pkl.dump(Toss_decision,open('Toss_decision.plk','wb'))

In [315]:
from collections import Counter
Counter(main_team)

Counter({'Sunrisers Hyderabad': 1,
         'Mumbai Indians': 1,
         'Gujarat Titans': 1,
         'Royal Challengers Bangalore': 1,
         'Kolkata Knight Riders': 1,
         'Kings XI Punjab': 1,
         'Chennai Super Kings': 1,
         'Rajasthan Royals': 1,
         'Delhi Capitals': 1})

In [316]:
pkl.dump(main_team,open('teams.pkl','wb'))

In [317]:
Venue=list(Model_df['venue'].unique())

In [318]:
Venue

['Rajiv Gandhi International Stadium, Uppal',
 'Sawai Mansingh Stadium',
 'Eden Gardens',
 'M Chinnaswamy Stadium',
 'Punjab Cricket Association Stadium, Mohali',
 'Sardar Patel Stadium, Motera',
 'Himachal Pradesh Cricket Association Stadium',
 'Brabourne Stadium',
 'Feroz Shah Kotla',
 'Rajiv Gandhi Intl. Cricket Stadium',
 'Wankhede Stadium',
 'Sheikh Zayed Stadium',
 'Dubai International Cricket Stadium',
 'OUTsurance Oval',
 "St George's Park",
 'MA Chidambaram Stadium, Chepauk',
 'Maharashtra Cricket Association Stadium',
 'Sharjah Cricket Stadium',
 'Holkar Cricket Stadium',
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
 'SuperSport Park',
 'Punjab Cricket Association IS Bindra Stadium, Mohali',
 'ACA-VDCA Stadium',
 'Feroz Shah Kotla Ground',
 'Dr DY Patil Sports Academy',
 'Kingsmead',
 'Green Park',
 'Shaheed Veer Narayan Singh International Stadium',
 'M. A. Chidambaram Stadium',
 'Barabati Stadium',
 'Saurashtra Cricket Association Stadium',
 'M. Chinnaswamy Stadium',
 'Newlands',
 'Buffalo Park',
 'De Beers Diamond Oval',
 'New Wanderers Stadium',
 'JSCA International Stadium Complex',
 'IS Bindra Stadium',
 'Vidarbha Cricket Association Stadium, Jamtha',
 'Subrata Roy Sahara Stadium']

In [319]:
pkl.dump(Venue,open('venue.pkl','wb'))

In [320]:
Season=list(Model_df['Season_year'].unique())

In [321]:
pkl.dump(Season,open('season.pkl','wb'))

In [322]:
import os
os.listdir('.')

['.ipynb_checkpoints',
 'app.py',
 'batsman_stat.pkl',
 'bowlers_stat.pkl',
 'city.pkl',
 'Data',
 'IPL_Prediction_Project_Relative_file.ipynb',
 'model.pkl',
 'season.pkl',
 'team.pkl',
 'teams.pkl',
 'Toss_decision.plk',
 'venue.pkl']

In [323]:
import sys
print(sys.executable)
print(sys.version)

C:\Users\abhis\anaconda3\python.exe
3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]

In [324]:
import os
print(os.getcwd())

C:\Users\abhis\IPL_win_Probability_ML